version: '3.8'

services:
  server:
    image: ${DOCKER_REGISTRY-}server
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 5000:8080
      - 5001:5001
    networks:
      - proxybackend

  server2:
    image: ${DOCKER_REGISTRY-}server2
    container_name: server2
    build:
      context: .
      dockerfile: server/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 6000:8080
      - 6001:8081
      - 5001:5001
    networks:
      - proxybackend

  server3:
    image: ${DOCKER_REGISTRY-}server3
    container_name: server3
    build:
      context: .
      dockerfile: server/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 7000:8080
      - 7001:8081
      - 5001:5001
    networks:
      - proxybackend

  server4:
    image: ${DOCKER_REGISTRY-}server4
    container_name: server4
    build:
      context: .
      dockerfile: server/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 8000:8080
      - 8001:8081
      - 5001:5001
    networks:
      - proxybackend

  server5:
    image: ${DOCKER_REGISTRY-}server5
    container_name: server5
    build:
      context: .
      dockerfile: server/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 9000:8080
      - 9001:8081
      - 5001:5001
    networks:
      - proxybackend

  loadbalancer:
    image: ${DOCKER_REGISTRY-}loadbalancer
    container_name: loadbalancer
    build:
      context: .
      dockerfile: loadbalancer/Dockerfile
    cpus: 1
    mem_limit: "0.5G"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - 3000:8080
      - 3001:8081
      - 3000:5001
      - 3001:5001
      - 5001:5001
    networks:
      - proxybackend


networks:
  proxybackend:
    name: proxybackend
    driver: bridge

