version: "3.8"

services:
  configsvr:
    image: mongo
    container_name: configsvr
    command: --configsvr --replSet configReplSet --port 27017
    ports:
      - "27017:27017"
    volumes:
      - configsvr_data:/data/db

  shard1:
    image: mongo
    container_name: shard1
    command: --shardsvr --replSet shard1ReplSet --port 27018
    ports:
      - "27018:27018"
    volumes:
      - shard1_data:/data/db

  shard2:
    image: mongo
    container_name: shard2
    command: --shardsvr --replSet shard2ReplSet --port 27019
    ports:
      - "27019:27019"
    volumes:
      - shard2_data:/data/db

  shard3:
    image: mongo
    container_name: shard3
    command: --shardsvr --replSet shard3ReplSet --port 27020
    ports:
      - "27020:27020"
    volumes:
      - shard3_data:/data/db

  shard4:
    image: mongo
    container_name: shard4
    command: --shardsvr --replSet shard4ReplSet --port 27021
    ports:
      - "27021:27021"
    volumes:
      - shard4_data:/data/db

  mongos:
    image: mongo
    container_name: mongos
    command: mongos --configdb configReplSet/configsvr:27017 --bind_ip_all
    ports:
      - "27022:27022"

volumes:
  configsvr_data:
  shard1_data:
  shard2_data:
  shard3_data:
  shard4_data:
